{% set name = "openfast" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
  sha256: 94da085f1d8861a93ab32b6b39335a403d182be0b5f7ff48f63d5805eb7f2b2c

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [not win]
    - flang                      # [win]
    - lld                        # [win]
    - make  # [not win]
    - cmake
    - ninja  # [win]
    - llvm-openmp  # [osx]
  host:
    - openblas
    - ucrt  # [win]
    - libgomp  # [linux or win]
  run:
    - libopenblas  # [win]
    - ucrt  # [win]
    - libgomp  # [linux or win]

test:
  commands:
    - openfast -h
    - FAST.Farm -h
    - aerodyn_driver -h
    - hydrodyn_driver -h
    - moordyn_driver -h
    - servodyn_driver -h
    - turbsim -h

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  recipe-maintainers:
    - rafmudaf
    - andrew-platt
    - deslaughter
    - gbarter
