{% set name = "openfast" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openfast/openfast/archive/v{{ version }}.tar.gz
  sha256: 7d4f7d79dae3eabed109da1117204dd6dfa53b01ef027051c2be2d5f8dbb3ecb
  # Download the tar-ball and do `openssl sha256 file.tar.gz` to update

# source:
#   git_url: https://github.com/openfast/openfast.git
#   git_rev: v{{ version }}
#   git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  choco:
    - mingw
#    - cmake
    - make
#    - ninja
  build:
    - {{ compiler('c') }} # [not win]
    - {{ compiler('cxx') }} # [not win]
    - {{ compiler('fortran') }} # [not win]
#    - {{ compiler('m2w64_fortran') }} # [win]
#    - {{ compiler('m2w64_cxx') }} # [win]
#    - {{ compiler('m2w64_c') }} # [win]
#    - make         # [not win]
    - cmake        # [not win]
    - llvm-openmp  # [osx or win]
    - libgomp      # [linux]
  host:
    - openblas
    - libblas
    - liblapack
    - libpgmath   # [win]

test:
  commands:
    - openfast -h
    - FAST.Farm -h
    - aerodyn_driver -h
    - hydrodyn_driver -h
    - moordyn_driver -h
    - servodyn_driver -h

about:
  home: https://github.com/openfast/openfast
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenFAST whole turbine simulation tool
  description: NREL-supported OpenFAST whole-turbine simulation code
  doc_url: http://openfast.readthedocs.io
  dev_url: https://github.com/openfast/openfast

extra:
  recipe-maintainers:
    - rafmudaf
    - openfast
